### PR TITLE
Added DUMPURL for fixing "Not able to find a sync_url in database - ERROR: 255 "

### PR DESCRIPTION
**Pull request by cryolune**
- [x] DUMPURL has been added in docker-compose.yml file.

issue #84

### CODE REVIEW

**Comment by dlebauer** [comment]
Awesome, thanks for submitting this PR!

Looks good, just need to check why the test and linter checks are failing (do you know @im-prakher ?)

**Comment by im-prakher** [comment]
@theakhiljha Implement this locally and make a commit,

**Comment by im-prakher** [comment]
@theakhiljha Implement this locally then make a commit,
`$git checkout -b temp`
`$ git checkout master`
`$ git merge temp`
`$ git branch -d temp`
This should work for linter test

**Comment by cryolune** [comment]
@im-prakher I tried to implement this locally and followed the commands you gave to fix the linter test issue but it didn't work.

**Pull request merged**
